Repository jupyterlab/extension-template, pull requests merged in 2023-07, with the labels that each got.

#27 Pin pydantic
  .github/workflows/check-tests.yml
  .github/workflows/main.yml
  README.md
Labels: maintenance

#31 Forbid empty author name
  copier.yml
Labels: enhancement

#32 Pin `copier` in the conda command
  README.md
Labels: documentation

#33 Improve error message for invalid author name
  copier.yml
Labels: documentation

#34 Multiple clean ups and some dep update
  template/.github/workflows/build.yml.jinja
  template/package.json.jinja
  template/pyproject.toml.jinja
  template/setup.py
  template/tsconfig.json
  template/{% if kind == 'server' %}jupyter-config{% endif %}/nb-config/{{python_name}}.json.jinja
  template/{% if test %}tsconfig.test.json{% endif %}
  template/{{python_name}}/__init__.py.jinja
Labels: enhancement

#37 Add CSS validator
  template/package.json.jinja
Labels: enhancement
