Repository jupyterlab/extension-template, pull requests merged in 2023-10, with the labels that each got.

#45 Fix default lab branch
  template/{% if test %}ui-tests{% endif %}/README.md
Labels: documentation

#47 Switch from hub to gh CLI
  template/.github/workflows/{% if test %}update-integration-tests.yml{% endif %}
Labels: enhancement

#49 Switch from hub to gh cli
  .github/workflows/update-workflows.yml
Labels: maintenance

#50 Add Python 3.12 classifier
  template/pyproject.toml.jinja
Labels: maintenance
